/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:5
-- pg_jsonschema::json_matches_schema
CREATE  FUNCTION "json_matches_schema"(
	"schema" json, /* pgrx::datum::json::Json */
	"instance" json /* pgrx::datum::json::Json */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'json_matches_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:10
-- pg_jsonschema::jsonb_matches_schema
CREATE  FUNCTION "jsonb_matches_schema"(
	"schema" json, /* pgrx::datum::json::Json */
	"instance" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_matches_schema_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:15
-- pg_jsonschema::jsonschema_is_valid
CREATE  FUNCTION "jsonschema_is_valid"(
	"schema" json /* pgrx::datum::json::Json */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonschema_is_valid_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:32
-- pg_jsonschema::jsonschema_validation_errors
CREATE  FUNCTION "jsonschema_validation_errors"(
	"schema" json, /* pgrx::datum::json::Json */
	"instance" json /* pgrx::datum::json::Json */
) RETURNS TEXT[] /* alloc::vec::Vec<alloc::string::String> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonschema_validation_errors_wrapper';
/* </end connected objects> */

