-- Add migration script here

CREATE ROLE stk_todo_superuser;

ALTER DATABASE stk_todo_db OWNER TO stk_todo_superuser;

GRANT CONNECT ON DATABASE stk_todo_db TO stk_todo_superuser;

GRANT USAGE ON SCHEMA public TO stk_todo_superuser;

GRANT create ON SCHEMA public TO stk_todo_superuser;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO stk_todo_superuser;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO stk_todo_superuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO stk_todo_superuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO stk_todo_superuser;

ALTER ROLE stk_todo_superuser SET search_path TO public;

create table todo (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz
);

insert into todo (task) values
  ('finish tutorial 0'), ('pat self on back');
