-- Add migration script here

CREATE ROLE stk_todo_superuser;

ALTER DATABASE stk_todo_db OWNER TO stk_todo_superuser;

ALTER USER stk_todo_superuser SET search_path TO public;

create table todos (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz
);

insert into todos (task) values
  ('finish tutorial 0'), ('pat self on back');
